//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WASE.pres", typeof(pres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;doc&gt;
        ///    &lt;brackets left=&quot;[&quot; right=&quot;]&quot; /&gt;
        ///    &lt;style name=&quot;Pink&quot; color=&quot;Magenta&quot;/&gt;
        ///    &lt;style name=&quot;Blue&quot; color=&quot;Blue&quot;/&gt;
        ///	&lt;style name=&quot;Green&quot; color=&quot;Green&quot;/&gt;
        ///	&lt;style name=&quot;Red&quot; color=&quot;Red&quot; fontStyle=&quot;Bold&quot;/&gt;
        ///    &lt;style name=&quot;Orange&quot; color=&quot;Orange&quot; fontStyle=&quot;Bold&quot;/&gt;
        ///
        ///	&lt;rule style=&quot;Pink&quot;&gt;@echo off&lt;/rule&gt;
        ///    &lt;rule style=&quot;Orange&quot;&gt;[%,&gt;]&lt;/rule&gt;
        ///    &lt;rule style=&quot;Red&quot;&gt;==&lt;/rule&gt;
        ///    
        ///
        ///
        ///    &lt;!--
        ///    Im never going to do this again!
        ///    --&gt;
        ///
        ///    &lt;rule style=&quot;Blue&quot;&gt;title&lt;/rule&gt;
        ///    &lt;rule style=&quot;Blu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string descFile_BAT {
            get {
                return ResourceManager.GetString("descFile_BAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;doc&gt;
        ///    &lt;brackets left=&quot;[&quot; right=&quot;]&quot; /&gt;
        ///    &lt;style name=&quot;Green&quot; color=&quot;Green&quot; fontStyle=&quot;Bold&quot; /&gt;
        ///    &lt;style name=&quot;Blue&quot; color=&quot;RoyalBlue&quot;/&gt;
        ///	&lt;style name=&quot;Yellow&quot; color=&quot;Yellow&quot;/&gt;
        ///	&lt;style name=&quot;Red&quot; color=&quot;Red&quot; fontStyle=&quot;Bold&quot;/&gt;
        ///    &lt;rule style=&quot;Green&quot;&gt;\[(.*?)\]&lt;/rule&gt;
        ///    &lt;rule style=&quot;Red&quot;&gt;\!\-\!(.*?)\!\-\!&lt;/rule&gt;
        ///	&lt;rule style=&quot;Red&quot;&gt;[=]&lt;/rule&gt;
        ///    &lt;rule style=&quot;Blue&quot;&gt;[&quot;]&lt;/rule&gt;
        ///
        ///        &lt;rule style=&quot;Yellow&quot;&gt;\{(.*?)\}&lt;/rule&gt;
        ///
        ///&lt;/doc&gt;.
        /// </summary>
        internal static string descFile_INI {
            get {
                return ResourceManager.GetString("descFile_INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon msi {
            get {
                object obj = ResourceManager.GetObject("msi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Program {
            get {
                object obj = ResourceManager.GetObject("Program", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WASE {
            get {
                object obj = ResourceManager.GetObject("WASE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WASE1 {
            get {
                object obj = ResourceManager.GetObject("WASE1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WASE32 {
            get {
                object obj = ResourceManager.GetObject("WASE32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WASE321 {
            get {
                object obj = ResourceManager.GetObject("WASE321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WASE32INST {
            get {
                object obj = ResourceManager.GetObject("WASE32INST", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WASE32INST1 {
            get {
                object obj = ResourceManager.GetObject("WASE32INST1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WASE64 {
            get {
                object obj = ResourceManager.GetObject("WASE64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WASE641 {
            get {
                object obj = ResourceManager.GetObject("WASE641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
